project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Possible Sharknados"
  author: "Jesus Rodriguez"
  page-footer:
    left: "Copyright 2025, Jesus Rodriguez"
  chapters:
    - index.qmd
    - final-exec-summary.qmd
    - final-intro.qmd
    - final-methods.qmd
    - final-results.qmd
    - final-conclusion.qmd
    - references.qmd
  appendices:
    - final-data-doc.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



