---
title: "Draft: Intro/Conclusions"
---

# Introduction

## A Real Life Sharknado?

There is a growing concern over the possibility of a real life *Sharknado*, a tornado that forms over water, gathers sharks in its powerful vortex, and then travels onto land, carrying the sharks with it. These sharknados wreak havoc all throughout the United States in locations like Los Angeles, New York City, and even Washington D.C. all the way down to Orlando, Florida raining sharks down from the sky. There have been circumstances where tornadoes have picked up animals such as fish and frogs, if one's imagination is not limited, one could see it be possible for tornadoes to carry sharks. Although this concept originates science fiction movie series, it raises serious questions on how thin the line between fiction and reality might be when it comes to such a catastrophic event. 

## Tornadoes and Sharks

To help figure out how a *sharknado* would be possible, the strenghts and conditions of tornadoes must be analyzed to see how they could carry these apex marine predators. 

### How Strong can a Tornado Be?

The Enhanced Fujita Scale (EF Scale), which is used to assign a tornado a rating based on estimated wind speeds. The scores and their estimated wind speeds go as follows:

-   EF0 (Weakest)

    -   65 - 85 mph

-   EF1

    -   86 - 110 mph

-   EF2

    -   111 - 135 mph

-   EF3

    -   136 - 165 mph

-   EF4

    -   166 - 200 mph

-   EF5 (Strongest)

    -   Over 200 mph

Minor damage such as broken tree branches and roof shingles being blown away can be expected from EF0 tornadoes. While on the other end of the spectrum, EF5 tornadoes can promise wind speeds that can decimate well built homes and infrastructure. These tornadoes can carry objects like cars with no trouble.

### Tornado or Waterspout?

This *sharknado* would need to have a tornado that forms over shark infested waters. A tornado that forms over water is usually classified as a waterspout. Waterspouts are not classified as tornadoes, so they are not given a score on the EF scale. If a waterspout moves on shore however, The National Weather Service classifies it as a tornado and issues a tornado warning for the area.

Waterspouts are generally broken into two categories: fair weather waterspouts and tornadic waterspouts. Fair weather waterspouts to put it simply are a less dangerous event that form during relatively calm weather and are not associated with thunderstorms. The phenonema of interest are tornadic waterspouts. These have the same characteristics of a land tornado, they are often accompanied by high winds, severe thunderstorms, large hail. It is essentially a tornado that forms over water, but it can also form by a tornado moving from land to water. If a *sharknado* would occur this is how it would form!

### Sharks in Infested Waters in the United Sates

Sharks are found in coastal waters along the East Coast, Gulf of Mexico, and the Caribbeans. These waters are where a *sharknado* would have to form.

Sharks vary greatly in size and weight. Some common sharks and their average adult weights include:

-   Atlantic Sharpnose

    -   15 - 25 lbs

-   Atlantic Blacktip

    -   66 - 200 lbs

-   Tiger

    -   850 - 1400 lbs

-   Hammerhead

    -   500 - 1000 lbs

-   Sandtiger

    -   200 - 350 lbs

-   The Great White

    -   1500 - 2400 lbs
    
The sharks that were commonly seen inside the *sharknado* were the tiger shark, the hammerhead shark, and of course, the great white shark.

## Can a Sharknado Actually Occur?

Is it possible to predict if a *sharknado* can happen in real life.  using exisiting data about sharks and tornadoes from years past?

To answer this burning question, a scrutinizing look at meteorological and marine data must be done.

# Conclusions

## Tornadic Waterspouts Powerful Enough to Carry Sharks *And* Makes Landfall is an Unlikely Event

Key findings suggest that a sharknado is not likely to occur. Waterspouts do tend to form in shark infested waters, but these are not powerful enough to lift sharks that can weight up to 2400 lbs and relocate them to land. 

### There is a Little Amount of Tornadoes with a High Enough EF Scale that form near the coasts





