# Preface {.unnumbered}

You are a data scientist for a mid-sized business, in a small group of 3-4 data scientists. You've been tasked with creating a report evaluating a scenario for your business. 
Your colleagues will also be evaluating the same scenario, and your reports will be used in aggregate to determine a consensus (or lack thereof) on the company's action. 
The reports will also be used to inform downsizing that is rumored to be coming - you want to ensure your report is better than your peers so that you aren't as easy to cut. 

You may talk to your peers who are assigned the same scenario, but you do not want to collaborate too closely, lest you both become targets of the rumored layoffs. 


---

I've scaffolded this report for you to make this process easier - as we talk about different sections of a report in class and read about how to create similar sections, you will practice by writing the equivalent section of your report.


The basic steps for this task are as follows:

- Identify the research question from the business question

What is the frequency of tornadoes that form in shark infested waters on the coastline happen to move inwards, and how common is it that these same tornadoes also have the strength to lift sharks from those waters?

Here is some databases I've found that may be able to help anser this question
```{r}
# shark data
library(readr)
Biological_Data_SBK <- read_csv("Biological _Data_SBK.csv")
View(Biological_Data_SBK)

# tornado data
library(readr)
StormEvents_details_ftp_v1_0_d1950_c20210803 <- read_csv("StormEvents_details-ftp_v1.0_d1950_c20210803.csv")
View(StormEvents_details_ftp_v1_0_d1950_c20210803)

# coastal data
library(sf)
CZMP_counties_2009 <- read_sf("CZMP_counties_2009/CZMP_counties_2009.shp")
View(CZMP_counties_2009)
```




- Identify data set(s) which are (1) publicly available (you don't have a budget to pay for private data) and (2) relevant to your task

    - (HW Week 6) Document your data sets in `draft-data-doc.qmd`

- Conduct a statistical analysis to support your answer to your research and business questions

    - Write a methods section for your business report corresponding to your statistical analysis

    - (HW Week 9) Draft of results section of business report with relevant graphics/visual aids in `draft-results.qmd`
    
- Write your report

    - (HW Week 10) Draft of Intro/Conclusion sections in `draft-intro-conclusions.qmd`
    
    - (HW Week 11) Draft of Executive summary section in `draft-exec-summary.qmd`
    
- Revise your report

    - (HW Week 12 -- not turned in) Revise your report
    
    - (HW Week 13) - Rough draft of report due. Create one or more qmd files for your report (you can overwrite or delete intro.qmd and summary.qmd), include the names of each file (in order) in `_quarto.yml`. You should use references (edit references.bib and use pandoc citations). Make sure your report compiles and looks reasonable in both html and pdf. 
    
    - Develop a presentation to go along with your report (Week 13). Create slides for your report using quarto. 

- Peer revise reports

    - Peer revise reports
    
    - (HW Week 14) - Make edits to your report from comments received from peer review

- Final report & presentation due